/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busquedabinaria;

import java.awt.HeadlessException;
import java.util.Arrays;
import javax.swing.JOptionPane;

public class Interfaz extends javax.swing.JFrame {

    int[] arrayNumeros;
    int index = 0, tamanioTotal, numeroBuscar;

    public Interfaz() {
        initComponents();
        setLocationRelativeTo(null);
        tamanioTotal = Integer.parseInt(JOptionPane.showInputDialog("¿Cuantos numeros seran introducidos?"));
        arrayNumeros = new int[tamanioTotal];
    }

    public void mostrarDatos() {
        String datosIntroducidos = "";
        for (int i = 0; i < index; i++) {
            datosIntroducidos += "[" + arrayNumeros[i] + "] ";
        }
        txtDatos.setText(datosIntroducidos);
    }

    public void metodoBurbuja() {
        int i, j, aux;
        for (i = 0; i < arrayNumeros.length - 1; i++) {
            for (j = 0; j < arrayNumeros.length - i - 1; j++) {
                if (arrayNumeros[j + 1] < arrayNumeros[j]) {
                    aux = arrayNumeros[j + 1];
                    arrayNumeros[j + 1] = arrayNumeros[j];
                    arrayNumeros[j] = aux;
                }
            }
        }
        mostrarDatos();
    }

    public int busquedaBinaria(int inicio, int fin) {
        int mitad = (inicio + fin) / 2;
        int auxTamanio = fin - inicio;

        System.out.println("");
        System.out.println("Buscando: " + numeroBuscar);
        System.out.println("Inicio: " + inicio + ", fin: " + fin);
        System.out.println("Middle: " + mitad);
        System.out.println("Array: " + Arrays.toString(arrayNumeros));
        System.out.println("Numero medio: " + arrayNumeros[mitad]);
        System.out.println("Tamaño: " + auxTamanio);
        System.out.println("");

        if (arrayNumeros[mitad] == numeroBuscar) {
            return mitad;
        } else if (auxTamanio == 1) {
            return -1;
        } else if (numeroBuscar > arrayNumeros[mitad]) {
            return busquedaBinaria(mitad, fin);
        } else {
            return busquedaBinaria(0, mitad);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnIntroducir = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        txtDatos = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBusqueda = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduce tu número:");

        btnIntroducir.setText("Introducir");
        btnIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducirActionPerformed(evt);
            }
        });

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        txtDatos.setEditable(false);

        jLabel2.setText("Numero a buscar:");

        btnBusqueda.setText("Buscar");
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDatos)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBusqueda)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIntroducir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                        .addComponent(btnReiniciar)
                        .addGap(18, 18, 18)
                        .addComponent(btnOrdenar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnIntroducir)
                    .addComponent(btnOrdenar)
                    .addComponent(btnReiniciar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(btnBusqueda, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(txtDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducirActionPerformed
        try {
            if (index + 1 > tamanioTotal) {
                JOptionPane.showMessageDialog(null, "No se pueden introducir mas numeros al array");
            } else {
                int nuevoNumero = Integer.parseInt(txtInput.getText());
                arrayNumeros[index] = nuevoNumero;
                index++;
            }
            txtInput.setText("");
            mostrarDatos();
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Solo se permiten numeros");
        }
    }//GEN-LAST:event_btnIntroducirActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        metodoBurbuja();
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        numeroBuscar = Integer.parseInt(txtBuscar.getText());
        int resultadoBusqueda = busquedaBinaria(0, tamanioTotal);
        if (resultadoBusqueda == -1) {
            JOptionPane.showMessageDialog(rootPane, "El numero " + numeroBuscar  + " no se encuentra en el array");
        } else {
            JOptionPane.showMessageDialog(rootPane, "El numero " + numeroBuscar  + " se encuentra en la posicion " + (resultadoBusqueda + 1));
        }
    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        index = 0;
        txtInput.setText("");
        txtDatos.setText("");
        txtBuscar.setText("");
        tamanioTotal = Integer.parseInt(JOptionPane.showInputDialog("¿Cuantos numeros seran introducidos?"));
        arrayNumeros = new int[tamanioTotal];
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnIntroducir;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDatos;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
